// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbtazfidmfunokpjfcin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJidGF6ZmlkbWZ1bm9rcGpmY2luIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNTUyMzQsImV4cCI6MjA2MDgzMTIzNH0.XONKgJ0pZnjQd4Wy-mfXRCv_2xDf-LQfxISEEjJJuWA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
